name: Publish Python Package

on:
  release:
    types: [published]

  workflow_dispatch: # For testing

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # History/tags required to generate version info
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install build
      - run: python -m build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  publish-package:
    needs: build-package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      # url: https://pypi.org/p/msmart-ng
      url: https://test.pypi.org/p/msmart-ng

    # Required for trusted publishing
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
    # - uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     user: __token__
    #     password: ${{ secrets.PYPI_API_TOKEN }}
