name: Publish Python Package

on:
  release:
    types: [published]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-wheel:
    uses: ./.github/workflows/build-wheel.yml

  publish-package:
    runs-on: ubuntu-latest
    needs: [build-wheel]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          # user: __token__
          password: ThiS_WILL_FAIL # ${{ secrets.PYPI_TOKEN }}
